//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MTracker.Resources {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Text {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Text() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("MTracker.Resources.Text", typeof(Text).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string CategoriesPageLabel {
            get {
                return ResourceManager.GetString("CategoriesPageLabel", resourceCulture);
            }
        }
        
        internal static string EntriesPageLabel {
            get {
                return ResourceManager.GetString("EntriesPageLabel", resourceCulture);
            }
        }
        
        internal static string SettingsPageLabel {
            get {
                return ResourceManager.GetString("SettingsPageLabel", resourceCulture);
            }
        }
        
        internal static string EnglishLabel {
            get {
                return ResourceManager.GetString("EnglishLabel", resourceCulture);
            }
        }
        
        internal static string RussianLabel {
            get {
                return ResourceManager.GetString("RussianLabel", resourceCulture);
            }
        }
        
        internal static string DiscardLabel {
            get {
                return ResourceManager.GetString("DiscardLabel", resourceCulture);
            }
        }
        
        internal static string ApplyLabel {
            get {
                return ResourceManager.GetString("ApplyLabel", resourceCulture);
            }
        }
        
        internal static string LanguageLabel {
            get {
                return ResourceManager.GetString("LanguageLabel", resourceCulture);
            }
        }
        
        internal static string CurrencyLabel {
            get {
                return ResourceManager.GetString("CurrencyLabel", resourceCulture);
            }
        }
        
        internal static string Restart {
            get {
                return ResourceManager.GetString("Restart", resourceCulture);
            }
        }
        
        internal static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        internal static string ChartPageLabel {
            get {
                return ResourceManager.GetString("ChartPageLabel", resourceCulture);
            }
        }
        
        internal static string MonthlyPieLabel {
            get {
                return ResourceManager.GetString("MonthlyPieLabel", resourceCulture);
            }
        }
        
        internal static string DailyBarsLabel {
            get {
                return ResourceManager.GetString("DailyBarsLabel", resourceCulture);
            }
        }
        
        internal static string DalyByMonthLabel {
            get {
                return ResourceManager.GetString("DalyByMonthLabel", resourceCulture);
            }
        }
        
        internal static string NewEntryNewPageLabel {
            get {
                return ResourceManager.GetString("NewEntryNewPageLabel", resourceCulture);
            }
        }
        
        internal static string NewEntryEditPageLabel {
            get {
                return ResourceManager.GetString("NewEntryEditPageLabel", resourceCulture);
            }
        }
        
        internal static string CategoryPickerLabel {
            get {
                return ResourceManager.GetString("CategoryPickerLabel", resourceCulture);
            }
        }
        
        internal static string EntryTitleEntryLabel {
            get {
                return ResourceManager.GetString("EntryTitleEntryLabel", resourceCulture);
            }
        }
        
        internal static string AmountEditorLabel {
            get {
                return ResourceManager.GetString("AmountEditorLabel", resourceCulture);
            }
        }
        
        internal static string CancelLabel {
            get {
                return ResourceManager.GetString("CancelLabel", resourceCulture);
            }
        }
        
        internal static string AcceptLabel {
            get {
                return ResourceManager.GetString("AcceptLabel", resourceCulture);
            }
        }
        
        internal static string NewCategoryNewPageLabel {
            get {
                return ResourceManager.GetString("NewCategoryNewPageLabel", resourceCulture);
            }
        }
        
        internal static string NewCategoryEditPageLabel {
            get {
                return ResourceManager.GetString("NewCategoryEditPageLabel", resourceCulture);
            }
        }
        
        internal static string NameLabel {
            get {
                return ResourceManager.GetString("NameLabel", resourceCulture);
            }
        }
        
        internal static string ColorLabel {
            get {
                return ResourceManager.GetString("ColorLabel", resourceCulture);
            }
        }
        
        internal static string RedLabel {
            get {
                return ResourceManager.GetString("RedLabel", resourceCulture);
            }
        }
        
        internal static string GreenLabel {
            get {
                return ResourceManager.GetString("GreenLabel", resourceCulture);
            }
        }
        
        internal static string BlueLabel {
            get {
                return ResourceManager.GetString("BlueLabel", resourceCulture);
            }
        }
        
        internal static string AboutPageLabel {
            get {
                return ResourceManager.GetString("AboutPageLabel", resourceCulture);
            }
        }
        
        internal static string GitHubLabel {
            get {
                return ResourceManager.GetString("GitHubLabel", resourceCulture);
            }
        }
        
        internal static string XamarinLabel {
            get {
                return ResourceManager.GetString("XamarinLabel", resourceCulture);
            }
        }
        
        internal static string FKSiSLabel {
            get {
                return ResourceManager.GetString("FKSiSLabel", resourceCulture);
            }
        }
        
        internal static string BerezhLabel {
            get {
                return ResourceManager.GetString("BerezhLabel", resourceCulture);
            }
        }
        
        internal static string InfoLabel {
            get {
                return ResourceManager.GetString("InfoLabel", resourceCulture);
            }
        }
        
        internal static string LicenseLabel {
            get {
                return ResourceManager.GetString("LicenseLabel", resourceCulture);
            }
        }
        
        internal static string CopyrightLabel {
            get {
                return ResourceManager.GetString("CopyrightLabel", resourceCulture);
            }
        }
    }
}
